image: skydb/dependencies-unstable
env:
  - GOPATH=/var/cache/drone
script:
  - go get github.com/stretchr/testify
  - go get ./...
  - make test
notify:
  email:
    recipients:
      - ben@skylandlabs.com
